[package]
name = "cep47"
version = "0.1.0"
authors = ["astro019 <dmitry.yakov7@gmail.com>"]
edition = "2018"

[dependencies]
casper-contract = "1.2.0"
casper-types = "1.2.0"
rand = { version="0.8", default-features=false }

[lib]
name = "cep47"
